#!/bin/sh

COMMIT_MSG_FILE=$1
CLEAN_MSG=$(awk '!/^#/ && NF { print; exit }' "$COMMIT_MSG_FILE")

REG_EXP='^(feat|fix|docs|style|refactor|test|chore)(\(.*\))?: .+'
BUMP_VERSION_PREFIX='^chore(\(.*\))?: Bump version to '
BUMP_VERSION_REG_EXP='^chore(\(.*\))?: Bump version to (pre-)?v[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+$'

if echo "$CLEAN_MSG" | grep -Eq "$BUMP_VERSION_PREFIX"; then
    if ! echo "$CLEAN_MSG" | grep -Eq "$BUMP_VERSION_REG_EXP"; then
        echo "========================================================="
        echo "❌ [ERROR]: Invalid bump version commit message format."
        echo "Format : chore: Bump version to <vx.y.z+NN>"
        echo "Allowed: chore(scope): Bump version to v1.2.3+45"
        echo "Allowed: chore(scope): Bump version to pre-v1.2.3+45"
        echo "========================================================="
        exit 1
    fi

    exit 0
fi

if ! echo "$CLEAN_MSG" | grep -Eq "$REG_EXP"; then
    echo "========================================================="
    echo "❌ [ERROR]: Invalid commit message format."
    echo "Format : <type>(<scope>): <subject>"
    echo "Allowed: feat, fix, docs, style, refactor, test, chore"
    echo "Example: feat(auth): add google oauth support"
    echo "========================================================="
    exit 1
fi
