targets:
  $default:
    builders:
      mhabit_proxy_builder|proxy_generator:
        enabled: true
        generate_for:
          include:
            - lib/**/*.dart
      source_gen|combining_builder:
        enabled: true
        options:
          preamble: "// coverage: ignore-file"
