// Mocks generated by Mockito 5.4.6 from annotations
// in mhabit/test/unit/models/app_sync/webdav_app_sync_group_subtasks_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mhabit/models/app_sync_server.dart' as _i3;
import 'package:mhabit/models/app_sync_server_form.dart' as _i8;
import 'package:mhabit/models/app_sync_tasks.dart' as _i6;
import 'package:mhabit/storage/db/db_helper.dart' as _i4;
import 'package:mhabit/storage/db/handlers/sync.dart' as _i10;
import 'package:mhabit/storage/db/handlers/sync_group.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite/sqflite.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_2 extends _i1.SmartFake implements Uri {
  _FakeUri_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppSyncServer_3 extends _i1.SmartFake implements _i3.AppSyncServer {
  _FakeAppSyncServer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDBHelper_4 extends _i1.SmartFake implements _i4.DBHelper {
  _FakeDBHelper_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_5 extends _i1.SmartFake implements _i5.Database {
  _FakeDatabase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppSyncSubTask].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSyncSubTask<T> extends _i1.Mock implements _i6.AppSyncSubTask<T> {
  MockAppSyncSubTask() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<T> run(_i6.AppSyncContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#run, [context]),
            returnValue:
                _i7.ifNotNull(
                  _i7.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#run, [context]),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(this, Invocation.method(#run, [context])),
          )
          as _i2.Future<T>);
}

/// A class which mocks [AppWebDavSyncServer].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppWebDavSyncServer extends _i1.Mock
    implements _i3.AppWebDavSyncServer {
  MockAppWebDavSyncServer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identity =>
      (super.noSuchMethod(
            Invocation.getter(#identity),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#identity),
            ),
          )
          as String);

  @override
  DateTime get createTime =>
      (super.noSuchMethod(
            Invocation.getter(#createTime),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#createTime)),
          )
          as DateTime);

  @override
  DateTime get modifyTime =>
      (super.noSuchMethod(
            Invocation.getter(#modifyTime),
            returnValue: _FakeDateTime_1(this, Invocation.getter(#modifyTime)),
          )
          as DateTime);

  @override
  _i3.AppSyncServerType get type =>
      (super.noSuchMethod(
            Invocation.getter(#type),
            returnValue: _i3.AppSyncServerType.unknown,
          )
          as _i3.AppSyncServerType);

  @override
  bool get configed =>
      (super.noSuchMethod(Invocation.getter(#configed), returnValue: false)
          as bool);

  @override
  Uri get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _FakeUri_2(this, Invocation.getter(#path)),
          )
          as Uri);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  String get password =>
      (super.noSuchMethod(
            Invocation.getter(#password),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#password),
            ),
          )
          as String);

  @override
  bool get ignoreSSL =>
      (super.noSuchMethod(Invocation.getter(#ignoreSSL), returnValue: false)
          as bool);

  @override
  bool get syncInLowData =>
      (super.noSuchMethod(Invocation.getter(#syncInLowData), returnValue: false)
          as bool);

  @override
  List<_i3.AppSyncServerMobileNetwork> get syncMobileNetworks =>
      (super.noSuchMethod(
            Invocation.getter(#syncMobileNetworks),
            returnValue: <_i3.AppSyncServerMobileNetwork>[],
          )
          as List<_i3.AppSyncServerMobileNetwork>);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  bool isSameConfig(
    _i3.AppSyncServer? other, {
    bool? withoutPassword = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #isSameConfig,
              [other],
              {#withoutPassword: withoutPassword},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool isSameServer(
    _i3.AppSyncServer? other, {
    bool? withoutPassword = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #isSameServer,
              [other],
              {#withoutPassword: withoutPassword},
            ),
            returnValue: false,
          )
          as bool);

  @override
  _i3.AppSyncServer copy({String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [], {#password: password}),
            returnValue: _FakeAppSyncServer_3(
              this,
              Invocation.method(#copy, [], {#password: password}),
            ),
          )
          as _i3.AppSyncServer);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.AppSyncServerForm toForm() =>
      (super.noSuchMethod(
            Invocation.method(#toForm, []),
            returnValue: _i7.dummyValue<_i8.AppSyncServerForm>(
              this,
              Invocation.method(#toForm, []),
            ),
          )
          as _i8.AppSyncServerForm);

  @override
  String toDebugString() =>
      (super.noSuchMethod(
            Invocation.method(#toDebugString, []),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#toDebugString, []),
            ),
          )
          as String);
}

/// A class which mocks [SyncGroupDBHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncGroupDBHelper extends _i1.Mock implements _i9.SyncGroupDBHelper {
  MockSyncGroupDBHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DBHelper get helper =>
      (super.noSuchMethod(
            Invocation.getter(#helper),
            returnValue: _FakeDBHelper_4(this, Invocation.getter(#helper)),
          )
          as _i4.DBHelper);

  @override
  _i5.Database get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeDatabase_5(this, Invocation.getter(#db)),
          )
          as _i5.Database);

  @override
  _i2.Future<Iterable<_i10.SyncDBCell>> loadAllGroupsSyncInfo({
    List<String>? columns = const [
      'id_',
      'group_uuid',
      'last_config_uuid',
      'last_mark',
      'last_mark_2',
      'dirty',
      'dirty_total',
    ],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadAllGroupsSyncInfo, [], {#columns: columns}),
            returnValue: _i2.Future<Iterable<_i10.SyncDBCell>>.value(
              <_i10.SyncDBCell>[],
            ),
          )
          as _i2.Future<Iterable<_i10.SyncDBCell>>);

  @override
  _i2.Future<bool> syncGroupDataToDb(
    _i6.WebDavSyncGroupData? data, {
    String? configId,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #syncGroupDataToDb,
              [data],
              {#configId: configId, #sessionId: sessionId},
            ),
            returnValue: _i2.Future<bool>.value(false),
          )
          as _i2.Future<bool>);

  @override
  _i2.Future<_i6.WebDavSyncGroupData?> loadGroupDataFromDb(
    String? uuid, {
    required String? configId,
    required String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadGroupDataFromDb,
              [uuid],
              {#configId: configId, #sessionId: sessionId},
            ),
            returnValue: _i2.Future<_i6.WebDavSyncGroupData?>.value(),
          )
          as _i2.Future<_i6.WebDavSyncGroupData?>);

  @override
  _i2.Future<void> clearGroupDirtyMark(
    _i6.WebDavSyncGroupData? data, {
    String? etag,
    String? configId,
    String? sessionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #clearGroupDirtyMark,
              [data],
              {#etag: etag, #configId: configId, #sessionId: sessionId},
            ),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);
}
