# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative "../../fastlane/deploy_lane_helper"
require_relative "../../fastlane/testflight_changelog_helper"

default_platform(:ios)

def testflight_android_changelog_metadata_dir(flavor)
  flavor_dir = File.expand_path(
    "../../android/app/src/#{flavor}/fastlane/metadata/android",
    __dir__
  )
  return flavor_dir if Dir.exist?(flavor_dir)

  shared_dir = File.expand_path("../../fastlane/metadata/android", __dir__)
  return shared_dir if Dir.exist?(shared_dir)

  UI.user_error!("No Android changelog metadata found for flavor #{flavor}")
end

platform :ios do
  desc "Clean environment"
  lane :clean do
    sh <<~EOS
      cd ../..
      .flutter/bin/flutter clean
      .flutter/bin/flutter precache --macos
      .flutter/bin/flutter pub get
    EOS
  end

  desc "Run Flutter unit tests"
  lane :test do
    sh "../../.flutter/bin/flutter test"
  end

  desc "Build Flutter app for a specified flavor (default: f_generic)"
  lane :build do |options|
    flavor = options[:flavor] || "f_generic"
    sh <<~EOS
      HOMEBREW_NO_AUTO_UPDATE=1 # disable homebrew's automatic updates.
      brew install cocoapods
      cd ../../macos
      bundle check || bundle install
      bundle exec pod install --no-repo-update
    EOS
    sh "../../.flutter/bin/flutter build macos --flavor #{flavor} --config-only"
  end

  desc "Push a new release build to the App Store"
  lane :deploy do |options|
    flavor = options[:flavor] || "f_store"
    do_build = DeployLaneHelper.option_enabled?(options, :build, default: true)
    do_clean = DeployLaneHelper.option_enabled?(options, :clean, default: true)
    force_build = DeployLaneHelper.option_enabled?(options, :force_build, default: false)
    track = options[:track] || "alpha"
    dry_run = DeployLaneHelper.dry_run_enabled?(options)
    pkg_path = File.expand_path("../../build/macos/Build/Fastlane/Release-#{flavor}", __dir__)
    pkg_artifact = File.join(pkg_path, "mhabit.pkg")
    artifact_exists = File.exist?(pkg_artifact)
    should_build = force_build || do_build

    if !do_build && !artifact_exists && !force_build
      UI.user_error!(
        "Missing existing build artifact at #{pkg_artifact}. Remove build:false or pass force_build:true."
      )
    end

    UI.important("force_build:true overrides build:false") if force_build && !do_build
    UI.message("Reusing existing PKG at #{pkg_artifact}") if artifact_exists && !should_build
    UI.message("No PKG found at #{pkg_artifact}; building before upload") if do_build && !artifact_exists && !force_build

    if do_clean && should_build
      clean()
    elsif do_clean
      UI.message("Skipping clean because the existing PKG will be reused")
    end

    if should_build
      build(flavor: flavor)
      build_mac_app(
        workspace: "Runner.xcworkspace",
        scheme: flavor,
        output_directory: pkg_path
      )
    end

    if track == "public"
      if dry_run
        DeployLaneHelper.report_dry_run_skip(
          action: "upload_to_app_store",
          artifact: pkg_artifact,
          track: track
        )
        next
      end

      upload_to_app_store(
        pkg: pkg_artifact
      )
    else
      changelog, localized_build_info = TestflightChangelogHelper.load(
        metadata_dir: testflight_android_changelog_metadata_dir(flavor),
        pubspec_path: File.expand_path("../../pubspec.yaml", __dir__),
        build_number: options[:changelog_build_number]&.to_s
      )
      upload_options = {
        pkg: pkg_artifact,
        uses_non_exempt_encryption: true,
        changelog: changelog,
        localized_build_info: localized_build_info
      }

      if dry_run
        DeployLaneHelper.report_dry_run_skip(
          action: "upload_to_testflight",
          artifact: upload_options[:pkg],
          track: track,
          locales: localized_build_info.keys
        )
        next
      end

      if track == "beta"
        upload_to_testflight(
          **upload_options,
          distribute_external: true,
          groups: ["Beta"]
        )
      else
        upload_to_testflight(**upload_options)
      end
    end
  end
end
