// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_COLLATION_API_G_H_
#define PIGEON_COLLATION_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace mhabit_collation {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const ::flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const ::flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  ::flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class CollationHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};



// An id/value pair for collation sorting.
//
// Generated class from Pigeon that represents data sent in messages.
class CollationItem {
 public:
  // Constructs an object setting all fields.
  explicit CollationItem(
    const std::string& id,
    const std::string& value);

  // Opaque identifier returned in the sorted result.
  const std::string& id() const;
  void set_id(std::string_view value_arg);

  // String whose collation order determines the sort position.
  const std::string& value() const;
  void set_value(std::string_view value_arg);

  bool operator==(const CollationItem& other) const;
  bool operator!=(const CollationItem& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static CollationItem FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class CollationHostApi;
  friend class PigeonInternalCodecSerializer;
  std::string id_;
  std::string value_;
};


// Request to sort [items] by the collation order of their [value]s.
//
// [locale] selects the ICU collation locale (Android) or is currently
// unused (iOS/macOS use the system locale via
// `localizedStandardCompare`).
//
// When [locale] is omitted, the platform uses its system-default
// collator. Returns the [CollationItem.id]s in collation order.
//
// Generated class from Pigeon that represents data sent in messages.
class CollationRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit CollationRequest(const ::flutter::EncodableList& items);

  // Constructs an object setting all fields.
  explicit CollationRequest(
    const ::flutter::EncodableList& items,
    const std::string* locale);

  const ::flutter::EncodableList& items() const;
  void set_items(const ::flutter::EncodableList& value_arg);

  const std::string* locale() const;
  void set_locale(const std::string_view* value_arg);
  void set_locale(std::string_view value_arg);

  bool operator==(const CollationRequest& other) const;
  bool operator!=(const CollationRequest& other) const;
  /// Returns a hash code value for the object. This method is supported for the benefit of hash tables.
  size_t Hash() const;
 private:
  static CollationRequest FromEncodableList(const ::flutter::EncodableList& list);
  ::flutter::EncodableList ToEncodableList() const;
  friend class CollationHostApi;
  friend class PigeonInternalCodecSerializer;
  ::flutter::EncodableList items_;
  std::optional<std::string> locale_;
};


class PigeonInternalCodecSerializer : public ::flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const ::flutter::EncodableValue& value,
    ::flutter::ByteStreamWriter* stream) const override;
 protected:
  ::flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    ::flutter::ByteStreamReader* stream) const override;
};

// Platform-native string collation.
//
// Generated interface from Pigeon that represents a handler of messages from Flutter.
class CollationHostApi {
 public:
  CollationHostApi(const CollationHostApi&) = delete;
  CollationHostApi& operator=(const CollationHostApi&) = delete;
  virtual ~CollationHostApi() {}
  // Returns [request.items]' ids reordered so that their corresponding
  // values are in collation order.
  virtual ErrorOr<::flutter::EncodableList> SortStrings(const CollationRequest& request) = 0;

  // The codec used by CollationHostApi.
  static const ::flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `CollationHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CollationHostApi* api);
  static void SetUp(
    ::flutter::BinaryMessenger* binary_messenger,
    CollationHostApi* api,
    const std::string& message_channel_suffix);
  static ::flutter::EncodableValue WrapError(std::string_view error_message);
  static ::flutter::EncodableValue WrapError(const FlutterError& error);
 protected:
  CollationHostApi() = default;
};
}  // namespace mhabit_collation
#endif  // PIGEON_COLLATION_API_G_H_
