# Copyright 2026 Fries_I23
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

<#
.SYNOPSIS
Checks whether the current Microsoft Store pending draft submission (if
any) was created by this pipeline, to avoid silently overwriting a draft
someone is preparing by hand in Partner Center.

.DESCRIPTION
`msstore submission get` falls back to the last published submission when
there's no pending draft yet (reported as an informational message on
stderr) — that case is safe, staging will create a fresh draft. If a
pending draft already exists, this compares its `Id` against the last Id
this pipeline recorded (passed in as KnownSubmissionId, sourced from the
MSSTORE_LAST_CI_SUBMISSION_ID repo/environment Variable, which
update_changelog.ps1 updates after a successful run via `gh variable
set`). Sets the `proceed` GitHub Actions output: "true" when safe to
continue, "false" when a foreign draft was found — in which case it also
prints a `::warning::` annotation; the caller is expected to skip every
step that would touch the submission (package staging, changelog
staging, finalize) when `proceed` is "false".

Earlier versions of this check used a marker substring written into the
submission's FriendlyName instead of an externally-tracked Id. That
doesn't work: FriendlyName is generated by Partner Center and silently
ignored by `submission updateMetadata` — verified by writing it and
reading the value back unchanged. Writing the marker into a real Listing
field (e.g. Description) instead was considered and rejected: that field
is customer-facing, so a marker left behind by a bug would ship to the
actual Store listing. An actions/cache-based version of the externally-
tracked Id was also tried and dropped: cache entries are evicted after 7
days unused, which (unlike a missing/wrong marker) leaves the pipeline
permanently blocked on this check until a human manually clears the
draft in Partner Center. A repo/environment Variable doesn't expire.

.PARAMETER ProductId
Microsoft Store product ID.

.PARAMETER KnownSubmissionId
The last submission Id this pipeline recorded, or empty if none is known
yet (e.g. first run, or the Variable was never set).
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProductId,

    [string]$KnownSubmissionId = ""
)

$ErrorActionPreference = "Stop"

. (Join-Path $PSScriptRoot "common.ps1")

$stderrLog = [System.IO.Path]::GetTempFileName()
try {
    $stdout = msstore submission get $ProductId 2>$stderrLog
    $stderrText = Get-Content -Raw $stderrLog -ErrorAction SilentlyContinue
}
finally {
    Remove-Item $stderrLog -ErrorAction SilentlyContinue
}

if ($stderrText -match "Could not find a Pending Submission") {
    Write-Host "No pending submission yet; safe to create a new one."
    Write-Output "proceed=true" >> $env:GITHUB_OUTPUT
    exit 0
}

$submission = ConvertFrom-MsstoreJson -Lines $stdout

if ($KnownSubmissionId -and $KnownSubmissionId -eq $submission.Id) {
    Write-Host "Pending submission Id $($submission.Id) matches the last Id this pipeline recorded; safe to continue."
    Write-Output "proceed=true" >> $env:GITHUB_OUTPUT
}
else {
    Write-Host "::warning::Found a pending Microsoft Store submission (Id $($submission.Id)) that doesn't match the last Id this pipeline recorded ($KnownSubmissionId). Skipping package/changelog/publish to avoid overwriting it. If it's safe to replace, finish or discard it in Partner Center first."
    Write-Output "proceed=false" >> $env:GITHUB_OUTPUT
}
