name: mhabit_proxy_builder
description: Internal build_runner proxy generator for mhabit.
publish_to: none

resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  analyzer: 12.1.0
  build: 4.0.6
  collection: ^1.17.0
  mhabit_proxy_annotation:
    path: ../mhabit_proxy_annotation
  source_gen: 4.2.3
