// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsCollationApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashCollationApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsCollationApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsCollationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsCollationApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsCollationApi(lhsKey, rhsKey) {
          if deepEqualsCollationApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsCollationApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashCollationApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashCollationApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashCollationApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashCollationApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashCollationApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashCollationApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// An id/value pair for collation sorting.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CollationItem: Hashable {
  /// Opaque identifier returned in the sorted result.
  var id: String
  /// String whose collation order determines the sort position.
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CollationItem? {
    let id = pigeonVar_list[0] as! String
    let value = pigeonVar_list[1] as! String

    return CollationItem(
      id: id,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      value,
    ]
  }
  static func == (lhs: CollationItem, rhs: CollationItem) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsCollationApi(lhs.id, rhs.id) && deepEqualsCollationApi(lhs.value, rhs.value)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CollationItem")
    deepHashCollationApi(value: id, hasher: &hasher)
    deepHashCollationApi(value: value, hasher: &hasher)
  }
}

/// Request to sort [items] by the collation order of their [value]s.
///
/// [locale] is used by Android (java.text.Collator) to select the ICU
/// collation locale. iOS/macOS ignore [locale] — they use
/// CFStringTransform(.toLatin) + localizedStandardCompare for a
/// contacts-style sort that is locale-independent.
///
/// When [locale] is omitted, the platform uses its system-default
/// collator. Returns the [CollationItem.id]s in collation order.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CollationRequest: Hashable {
  var items: [CollationItem]
  var locale: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CollationRequest? {
    let items = pigeonVar_list[0] as! [CollationItem]
    let locale: String? = nilOrValue(pigeonVar_list[1])

    return CollationRequest(
      items: items,
      locale: locale
    )
  }
  func toList() -> [Any?] {
    return [
      items,
      locale,
    ]
  }
  static func == (lhs: CollationRequest, rhs: CollationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsCollationApi(lhs.items, rhs.items) && deepEqualsCollationApi(lhs.locale, rhs.locale)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CollationRequest")
    deepHashCollationApi(value: items, hasher: &hasher)
    deepHashCollationApi(value: locale, hasher: &hasher)
  }
}

private class CollationApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CollationItem.fromList(self.readValue() as! [Any?])
    case 130:
      return CollationRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CollationApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CollationItem {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CollationRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CollationApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CollationApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CollationApiPigeonCodecWriter(data: data)
  }
}

class CollationApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CollationApiPigeonCodec(readerWriter: CollationApiPigeonCodecReaderWriter())
}

/// Platform-native string collation.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CollationHostApi {
  /// Returns [request.items]' ids reordered so that their corresponding
  /// values are in collation order.
  func sortStrings(request: CollationRequest) throws -> [String]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CollationHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CollationApiPigeonCodec.shared }
  /// Sets up an instance of `CollationHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CollationHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Returns [request.items]' ids reordered so that their corresponding
    /// values are in collation order.
    let sortStringsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.mhabit.CollationHostApi.sortStrings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sortStringsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! CollationRequest
        do {
          let result = try api.sortStrings(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sortStringsChannel.setMessageHandler(nil)
    }
  }
}
