# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require_relative "../../fastlane/deploy_lane_helper"

default_platform(:android)

def android_release_aab_path(flavor)
  File.expand_path(
    "../../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab",
    __dir__
  )
end

default_platform(:android)

platform :android do
  desc "Clean environment"
  lane :clean do
    sh <<~EOS
      cd ../..
      .flutter/bin/flutter clean
      .flutter/bin/flutter pub get
    EOS
  end

  desc "Run Flutter unit tests"
  lane :test do
    sh "../../.flutter/bin/flutter test"
  end

  desc "Build Flutter appbundle for a specified flavor (default: f_generic)"
  lane :build do |options|
    flavor = options[:flavor] || "f_generic"
    sh "../../.flutter/bin/flutter build appbundle --flavor #{flavor}"
  end

  desc "Update Information to Google Play Store"
  lane :update_play_store do |options|
    flavor = options[:flavor] || "f_store"
    meta_path = options[:meta_path] || "app/src/#{flavor}/fastlane/metadata/android"
    track = options[:track]
    dry_run = DeployLaneHelper.dry_run_enabled?(options)

    upload_params = {
      metadata_path: meta_path,
      skip_upload_apk: true,
      skip_upload_aab: !(options[:aab] || false),
      skip_upload_metadata: !(options[:metadata] || false),
      skip_upload_changelogs: !(options[:changelog] || false),
      skip_upload_images: !(options[:images] || false),
      skip_upload_screenshots: !(options[:screenshots] || false)
    }
    unless upload_params[:skip_upload_aab]
      upload_params[:aab] = "../build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab"
      upload_params[:track] = track if track
    end

    if dry_run
      DeployLaneHelper.report_dry_run_skip(
        action: "supply",
        artifact: upload_params[:aab],
        track: track,
        metadata_path: meta_path
      )
      next
    end

    supply(upload_params)
  end

  desc "Deploy to Google Play Store"
  lane :deploy_play_store do |options|
    flavor = options[:flavor] || "f_store"
    meta_path = options[:meta_path] || "app/src/#{flavor}/fastlane/metadata/android"
    do_build = DeployLaneHelper.option_enabled?(options, :build, default: true)
    do_clean = DeployLaneHelper.option_enabled?(options, :clean, default: true)
    force_build = DeployLaneHelper.option_enabled?(options, :force_build, default: false)
    track = options[:track]
    dry_run = DeployLaneHelper.dry_run_enabled?(options)
    aab_path = android_release_aab_path(flavor)
    artifact_exists = File.exist?(aab_path)
    should_build = force_build || do_build

    if !do_build && !artifact_exists && !force_build
      FastlaneCore::UI.user_error!(
        "Missing existing build artifact at #{aab_path}. Remove build:false or pass force_build:true."
      )
    end

    upload_params = {
      sync_image_upload: true,
      metadata_path: meta_path,
      aab: aab_path
    }
    upload_params[:track] = track if track

    FastlaneCore::UI.important("force_build:true overrides build:false") if force_build && !do_build
    FastlaneCore::UI.message("Reusing existing AAB at #{aab_path}") if artifact_exists && !should_build
    FastlaneCore::UI.message("No AAB found at #{aab_path}; building before upload") if do_build && !artifact_exists && !force_build

    if do_clean && should_build
      clean()
    elsif do_clean
      FastlaneCore::UI.message("Skipping clean because the existing AAB will be reused")
    end

    build(flavor: flavor) if should_build

    if dry_run
      DeployLaneHelper.report_dry_run_skip(
        action: "upload_to_play_store",
        artifact: upload_params[:aab],
        track: track,
        metadata_path: meta_path
      )
      next
    end

    upload_to_play_store(upload_params)
  end
end