name: Analyze CI

on:
  workflow_call:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup_flutter
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v5
