name: Build Linux Flatpak

on:
  workflow_call:
    inputs:
      arch:
        description: Target architecture (x64, arm64)
        type: string
      flatpak-arch:
        description: Target architecture for Faltpak (x86_64, aarch64)
        type: string
      flatpak-name:
        description: Name for Flatpak file
        type: string
        required: false
        default: ""
      retention-days:
        description: >
          Duration after which artifact will expire in days.
          0 means using default retention.
        type: number
        default: 0
    outputs:
      flatpak-artifact-id:
        description: artifact-id for generated Flatpak file
        value: ${{ jobs.build-flatpak.outputs.flatpak-artifact-id }}
      flatpak-name:
        value: ${{ jobs.build-flatpak.outputs.flatpak-name }}

jobs:
  pre-build:
    runs-on: ubuntu-22.04
    outputs:
      run-build: ${{ steps.check.outputs.run-build }}
      runner: ${{ steps.check.outputs.runner }}
      flatpak-arch: ${{ steps.check.outputs.flatpak-arch }}
    steps:
      - id: check
        run: |
          if [[ "${{ inputs.arch }}" == "x64" ]]; then
            echo "run-build=true" >> $GITHUB_OUTPUT
            # symbol `g_once_init_enter_pointer`` was introduced in glib>=2.80,
            # fallback build host to ubuntu-22.04 for better compatibility.
            # refs: https://github.com/cirruslabs/docker-images-flutter/issues/337.
            echo "runner=ubuntu-22.04" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.arch }}" == "arm64" ]]; then
            echo "run-build=true" >> $GITHUB_OUTPUT
            echo "runner=ubuntu-22.04-arm" >> $GITHUB_OUTPUT
          else
            echo "run-build=false" >> $GITHUB_OUTPUT
          fi

  build:
    name: "Build Linux Bundle"
    needs:
      - pre-build
    runs-on: ${{ needs.pre-build.outputs.runner }}
    if: ${{ needs.pre-build.outputs.run-build == 'true' }}
    env:
      BUNDLE_NAME: linux-bundle-${{ inputs.arch }}
    outputs:
      runner: ${{ needs.pre-build.outputs.runner }}
      bundle-path: ${{ steps.build.outputs.path }}
      bundle-name: ${{ env.BUNDLE_NAME }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_flutter
      - id: build
        uses: ./.github/actions/build_linux
        with:
          arch: ${{ inputs.arch }}
      - name: Upload Bundle
        id: upload-bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUNDLE_NAME }}
          path: ${{ steps.build.outputs.path }}
          if-no-files-found: error
          retention-days: 1

  build-flatpak:
    name: "Build linux Flatpak Installer"
    needs:
      - build
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    runs-on: ${{ needs.build.outputs.runner }}
    outputs:
      flatpak-artifact-id: ${{ steps.upload-bundle.outputs.artifact-id }}
      flatpak-name: ${{ env.FLATPAK_BUNDLE }}
    env:
      FLATPAK_ARCH: ${{ inputs.flatpak-arch }}
      FLATPAK_BUNDLE: >
        ${{ inputs.flatpak-name != '' && inputs.flatpak-name ||
        format('mhabit-{0}.flatpak', inputs.flatpak-arch) }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Bundle
        id: fetch-bundle-step
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.bundle-name }}
          path: ${{ needs.build.outputs.bundle-path }}
          github-token: ${{ secrets.APP_RELEASE_TOKEN }}
      - run: ls -al ${{ needs.build.outputs.bundle-path }}
      - name: Build .flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: ${{ env.FLATPAK_BUNDLE }}
          manifest-path: configs/flatpak_builder/io.github.friesi23.mhabit.yml
          arch: ${{ env.FLATPAK_ARCH }}
          branch: main
          upload-artifact: false
      - run: md5sum ${{ env.FLATPAK_BUNDLE }}
      - name: Upload Bundle
        id: upload-bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FLATPAK_BUNDLE }}
          path: ${{ env.FLATPAK_BUNDLE }}
          if-no-files-found: error
          retention-days: ${{ inputs.retention-days }}
