name: Test CI

on:
  workflow_call:

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup_flutter
      - name: Run app and package test suites
        run: dart run melos run test-ci
      - uses: actions/upload-artifact@v7
        if: success() || failure()
        with:
          name: flutter-unittest-result
          path: test_report.log
      - uses: actions/upload-artifact@v7
        if: success() || failure()
        with:
          name: flutter-package-unittest-result
          path: build/test-results/flutter/*.json
      - uses: actions/upload-artifact@v7
        if: success() || failure()
        with:
          name: dart-package-unittest-result
          path: build/test-results/dart/*.json

  # android-test:
  #   name: Android Unit Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: ./.github/actions/setup_flutter
  #     - uses: ./.github/actions/setup_jdk
  #     - name: Run Android unit tests
  #       run: cd android && ./gradlew :app:testF_genericDebugUnitTest --console=plain
  #     - uses: actions/upload-artifact@v7
  #       if: success() || failure()
  #       with:
  #         name: android-unittest-xml
  #         path: build/app/test-results/testF_genericDebugUnitTest/TEST-*.xml
