name: Test CI

on:
  workflow_call:

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_flutter
      - run: |
          set -o pipefail
          flutter test --machine | tee test_report.log
          set +o pipefail
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: flutter-unitTest-output
          path: test_report.log

  report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      checks: write
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: flutter-unitTest-output
          name: flutter test
          path: test_report.log
          reporter: flutter-json
