name: Check PR

on:
  pull_request:
    branches:
      - main
      - weblate-translation

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  analyzing:
    uses: ./.github/workflows/_analyze.yml

  checking:
    uses: ./.github/workflows/_check.yml

  testing:
    uses: ./.github/workflows/_test.yml
