name: Merge request checking

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyzing:
    uses: ./.github/workflows/_analyze.yml

  testing:
    uses: ./.github/workflows/_test.yml
