name: Build and release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build-android:
    name: Build android process
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java SDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Flutter action
        uses: subosito/flutter-action@v2.9.1
        with:
          channel: stable
          flutter-version: 3.7.12

      - name: Build key.properties
        run: |
          echo keyPassword=\${{ secrets.APP_SIGN_KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.APP_SIGN_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.APP_SIGN_KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
          echo storeFile=key.jks >> ${{env.PROPERTIES_PATH}}
          echo "${{ secrets.APP_SIGN_KEY_JKS }}" | base64 --decode > android/app/key.jks

      - name: Pub Get Packages
        run: flutter pub get

      - name: Unit test
        run: flutter test

      - name: Build release APPBUNDLE
        run: flutter build appbundle --release

      - name: Build release APK
        run: flutter build apk --release

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: >
            build/app/outputs/apk/debug/app-debug.apk,
            build/app/outputs/apk/release/app-release.apk,
            build/app/outputs/bundle/release/app-release.aab
          token: ${{ secrets.APP_RELEASE_TOKEN }}
